config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :admin_users
      resources :super_users
      resources :plants
      resources :products
      resources :use_parts

      root to: "users#index"
    end
  resources :use_parts

  get 'use_parts/index'
  get 'use_parts/edit'
  get 'use_parts/update'
  get 'use_parts/show'
  get 'use_parts/new'

  resources :products do
    member do
      get :use
      post :do_use
    end

    member do
      get :add
      post :add_product
    end
    collection do
      post :print_labels
    end
  end

  # devise_for :users
  devise_for :users, controllers: {registrations:'users/registrations'}

  root 'home#index'

  get 'home/index'

end

app/models/use_part.rb
class UsePart < ApplicationRecord
  belongs_to :product, optional: true
end

app/controllers/admin/use_parts_controller.rb
module Admin
  class UsePartsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/use_parts_controller.rb
class UsePartsController < ApplicationController
  before_action :set_use_part, only: [:show, :edit, :update, :destroy]

  def index
    @use_parts = UsePart.all
    # @use_part = UsePart.all
  end

  def edit
  end

  def update
  end

  def show
  end

  def new
    @use_part = UsePart.new
  end


  def create
    @use_part = UsePart.new(use_part_params)

    respond_to do |format|
      if @use_part.save
        format.html { redirect_to @use_part, notice: 'UsePart was successfully created.' }
        format.json { render :show, status: :created, location: @use_part }
      else
        format.html { render :new }
        format.json { render json: @use_part.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_use_part
      @use_part = UsePart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def use_part_params
      params.require(:use_part).permit(:qty)
    end
end

app/helpers/use_parts_helper.rb
module UsePartsHelper
end

app/views/use_parts/_form.html.erb
<%#= form_for(@use_part) do |form| %>

<%= form_with model: @use_part do |form| %>
  <% if @use_part.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(use_part.errors.count, "error") %> prohibited this use_part from being saved:</h2>

      <ul>
        <% use_part.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Product_id %><br>
    <%= form.text_field :product_id %><br>
    <%= form.label :quantity %><br>
    <%= form.text_field :qty %>
    <br><br>
  </div>
  <div class="actions">
    <%= form.submit %>
   
  </div>
<% end %>

app/views/use_parts/edit.html.erb
<h1>UseParts#edit</h1>
<p>Find me in app/views/use_parts/edit.html.erb</p>

app/views/use_parts/index.html.erb
<h1>UseParts#index</h1>
<p>Find me in app/views/use_parts/index.html.erb</p>


<br>

<table class='table'>
  <thead>
    <tr>
      <th>ID</th>
      <th>Qty</th>
      
      <th colspan="3"></th>

    </tr>
  </thead>

  <tbody>
    <% @use_parts.each do |use_part| %>
      <tr>
        <td><%= use_part.id %></td>
        <td><%= use_part.qty %></td>
        
        <td><%= link_to 'Show', use_part %></td>
        <td><%= link_to 'Edit', edit_product_path(use_part) %></td>
        <td><%= link_to 'Destroy', use_part, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'New use part', new_use_part_path %>

app/views/use_parts/new.html.erb
<h1>UseParts#new</h1>
<p>Find me in app/views/use_parts/new.html.erb</p>
<%= render 'form', product: @product %>

<%= link_to 'Back', use_parts_path %>

app/views/use_parts/show.html.erb
<h1>UseParts#show</h1>
<p>Find me in app/views/use_parts/show.html.erb</p>
Used: <%= @use_part.qty %>

app/views/use_parts/update.html.erb
<h1>UseParts#update</h1>
<p>Find me in app/views/use_parts/update.html.erb</p>