config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :admin_users
      resources :super_users
      resources :plants
      resources :products
      resources :use_parts

      root to: "users#index"
    end
  resources :use_parts

  get 'use_parts/index'
  get 'use_parts/edit'
  get 'use_parts/update'
  get 'use_parts/show'
  get 'use_parts/new'

  resources :products do
    member do
      get :use
      post :do_use
    end

    member do
      get :add
      post :add_product
    end
    collection do
      post :print_labels
    end
  end

  # devise_for :users
  devise_for :users, controllers: {registrations:'users/registrations'}

  root 'home#index'

  get 'home/index'

end

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-md bg-dark navbar-dark">
  <!-- Brand -->
  <% if user_signed_in? && current_user.plant_id? %>
    <!-- <a class="navbar-brand" href="#">Our Logo</a> -->
   <!-- Plant.all.map do |plant| [plant.name.capitalize , plant.id]  -->

    <%= link_to current_user.plant.name.capitalize, products_path, class: 'navbar-brand' %>
  <% else %>
    <%= link_to "Our Logo", root_path, class: 'navbar-brand' %>
  <% end %>
  <!-- Toggler/collapsibe Button -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!-- Navbar links -->
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav  ml-auto">
      <% if !user_signed_in? %>
        
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "btn btn-outline-primary custom-login" %>
        </li>
        <li class="nav-item">
          <% if current_user.try(:type) == 'AdminUser' %>
            <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-outline-success"  %>
          <% end %>
        </li>
      <% else %>
        <% if current_user.try(:type) == 'AdminUser' %>
          <li class="nav-user-name" style="color:red;">
            <%= current_user.first_name.capitalize + ' ' + current_user.last_name.capitalize %>
          </li>
        <% elsif  current_user.try(:type) == 'SuperUser' %>
          <li class="nav-user-name" style="color:green;">
            <%= current_user.first_name.capitalize + ' ' + current_user.last_name.capitalize %>
          </li>
        <% else %>
          <li class="nav-user-name">
            <%= current_user.first_name.capitalize + ' ' + current_user.last_name.capitalize %>
          </li>  
        <% end %>

        <% if current_user.try(:type) == 'AdminUser' || current_user.try(:type) == 'SuperUser' %> 
          <li class="nav-item">
            <%= link_to "Admin Dashboard", admin_root_path, class: "btn btn-outline-info nav-buttons custom-class"%>
          </li>
        <% end %>

        <li class="nav-item">
          <%= link_to "Logout", destroy_user_session_path, method: :delete , class: "btn btn-outline-warning nav-buttons custom-class"%>
        </li>
      <% end %>
    </ul>
  </div>
</nav>