config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :admin_users
      resources :super_users
      resources :plants
      resources :products
      resources :use_parts

      root to: "users#index"
    end
  resources :use_parts

  get 'use_parts/index'
  get 'use_parts/edit'
  get 'use_parts/update'
  get 'use_parts/show'
  get 'use_parts/new'

  resources :products do
    member do
      get :use
      post :do_use
    end

    member do
      get :add
      post :add_product
    end
    collection do
      post :print_labels
    end
  end

  # devise_for :users
  devise_for :users, controllers: {registrations:'users/registrations'}

  root 'home#index'

  get 'home/index'

end

app/models/product.rb
class Product < ApplicationRecord

	belongs_to :plant

	has_one_attached :featured_image, dependent: :destroy

	def featured_image_url
	  if self.featured_image.attachment
	    self.featured_image.attachment.service_url
	  end
	end

	after_create :generate_code
	# mount_uploader :image, ImageUploader

	enum status: { active: 0, obsolete: 1}

	def generate_code
	  self.url = SecureRandom.hex
	  # self.url = product_path
	  save
	end


	def self.search(search)
	  if search
	    
	    # where('description ILIKE ? OR id::text LIKE ?', "%#{search}%", "%#{search}%")
	    where('description ILIKE ? OR item_no ILIKE? OR supplier_number ILIKE ? OR location ILIKE ? OR supplier_name ILIKE ? OR manufacturer_name ILIKE ? OR manufacturer_no ILIKE ?', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")

	  else
	    # find(:all)
	    
	    Product.all

	    
	  end
	end



end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # before_action :set_product, only: [:show, :edit, :update, :destroy, :new_qty, :do_use, :use]
  before_action :authenticate_user!
  before_action :set_product, only: %i[ show edit update destroy use do_use add add_product]
  
  # GET /products
  # GET /products.json
  helper_method :sort_column, :sort_direction
  def index
    # @products = Product.all
    if current_user.try(:type) == 'SuperUser'
      @products = Product.order(sort_column + " " + sort_direction).search(params[:search]).paginate(page: params[:page], per_page: 30)
    elsif 
      @products = Product.where(plant_id: current_user.plant_id).order(sort_column + " " + sort_direction).search(params[:search]).paginate(page: params[:page], per_page: 30)
    # @products = Product.order(params[:sort])
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    # respond_to do |format|
      # format.html
      # format.pdf do
        # logo = Rails.root + current_user.logo.url(:thumb).sub!(/\?.+\Z/, '')
        # # logo at: [0,900], height: 161, width: 250
        # pdf = InvoicePdf.new(@invoice, view_context)
        # pdf = Prawn::Document.new
        # pdf.text"Hello Ovi"
        # send_data pdf.render, filenamme: "product_#{@product.name}.pdf",
                              # filename: "invoice_#{sprintf("%05d", @invoice.invoice_number)}.pdf",
                              # type: "application/pdf",
                              # disposition: "inline"

      # end
    # end

  end

  # GET /products/new
  def new
    @product = Product.new
  end

  
  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

 def use
 end

 def do_use
    if @product.qty >= params[:qty].to_i
      @product.update qty: @product.qty - params[:qty].to_i
     redirect_to @product, notice: "Product was successfully updated."
    else
      @product.errors.add(:qty, "more than available quantity")
     render :use
    end
 end

# <<<<<<< Updated upstream
  

  def print_labels


    # selected_products = Product.where id: params[:products_ids]
    
    # GenerateSidePdfJob.perform_later


    selected_products = Product.where id: params[:products_ids]
    # selected_products = Product.where("id in (?)", params[:products_ids])
     ############### Big QR #########################
             # labels = Prawn::Labels.render(selected_products, :type => "Avery5160") do |pdf, selected_product|
             #   pdf.svg QrCode.call(product_url(selected_product)), :at => [5,68], :width => 65, :height => 65, :align => :left # [5 is x and 70 is y]
             #   pdf.draw_text selected_product.description.upcase.truncate(20),:style => :bold, :at => [75,55], :size => 10, overflow: :truncate
             #   pdf.draw_text "Supp.#: " + selected_product.supplier_number, :at => [75,35], :size => 9
             #   pdf.draw_text "Location: " + selected_product.supplier_number, :at => [75,15], :size => 9
               
             # end
         ############### Big QR #########################
         ############### Small QR #########################
             labels = Prawn::Labels.render(selected_products, :type => "Avery5160") do |pdf, selected_product|
               if selected_product.description
                 pdf.draw_text selected_product.description.upcase.truncate(29),:style => :bold, :at => [8,50], :size => 10, overflow: :truncate
               end
               pdf.svg QrCode.call(product_url(selected_product)), :at => [8,45], :width => 45, :height => 45, :align => :left # [5 is x and 70 is y]
               pdf.draw_text "Item #: " + selected_product.item_no.upcase.truncate(20), :at => [60,30], :size => 9
               if selected_product.location
                 pdf.draw_text "Location: " + selected_product.location.upcase.truncate(12), :at => [60,15], :size => 9
               end
               if selected_product.manufacturer_no
                 pdf.draw_text "Manuf.#: " + selected_product.manufacturer_no.upcase.truncate(20), :at => [60,2], :size => 9
               end
             end
         ############### Small QR #########################


             send_data labels, :filename => "labels.pdf", :type => "application/pdf"
    # redirect_to products_path
  end
# =======
 def add
 end

 def add_product
  if @product.qty >= params[:qty].to_i
    @product.update qty: @product.qty + params[:qty_add].to_i
    redirect_to @product, notice: "Product was successfully updated."
  else
    @product.errors.add(:qty, "more than available quantity")
    render :add
  end
 end

# >>>>>>> Stashed changes

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:id, :name, :url, :qty, :image, :description, :supplier_number, 
                                      :item_no, :location, :supplier_name, :status, :plant_id, :featured_image, :manufacturer_name,
                                      :manufacturer_no)
    end

    def sort_column
      params[:sort] || "id"
    end

    def sort_direction
      # %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
      params[:direction] || "asc"
    end

    
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="card card-body bg-light form-card">
  <%= form_with(model: product) do |form| %>
    <% if product.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

        <ul>
          <% product.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <!-- <div class="field"> -->
      <%#= form.label :name %>
      <%#= content_tag :div, 'data-controller': 'scanner' do %>
        <%#= content_tag :canvas, nil, width: 350, height: 240, 'data-scanner-target': 'canvas' %>
        <%#= form.text_field :name, id: 'lolz', class: 'form-control ', 'data-scanner-target': 'output' %>
        <%#= form.label :url %>
        <%#= form.text_field :url, class: 'form-control' %>
        
      <%# end %>
    <!-- </div> -->
    <div class="field">
      <%= form.label :description %><br>
      <%= form.text_field :description %>
    </div>
    <div class="field">
      <%= form.label :item_no %><br>
      <%= form.text_field :item_no %>
    </div>

    <div class="field">
      <%= form.label :quantity %><br>
      <%= form.text_field :qty %>
    </div>

    <div class="field">
      <%= form.label :supplier_number %><br>
      <%= form.text_field :supplier_number %>
    </div>
    <div class="field">
      <%= form.label :location %><br>
      <%= form.text_field :location %>
    </div>
    <div class="field">
      <%= form.label :supplier_name %><br>
      <%= form.text_field :supplier_name %>
    </div>
    <div class="field">
      <%= form.label :manufacturer_name %><br>
      <%= form.text_field :manufacturer_name %>
    </div>
    <div class="field">
      <%= form.label :manufacturer_no %><br>
      <%= form.text_field :manufacturer_no %>
    </div>
    <!-- <div class="field">
      <%#= form.label :plant %><br>
      <%#= form.collection_select(:plant_id, Plant.all, :id, :name_for_select, prompt: true) %>
    </div> -->
    <div class="field">
     
      <%= form.hidden_field :plant_id, :value => current_user.plant_id %>
      
    </div>

    <div class="field">
      <%= form.label :image %><br>
      <%= form.file_field :featured_image, class: "glyphicon glyphicon-download-alt" %>
    </div>

    <!-- <div class="field"> -->
      <%= form.label :activ %>
      <label class="switch">
        <%= form.check_box :status,{}, "active", "obsolete" %>
        <span class="slider round">
        </span>
      </label>
      <!-- <div class="ie-radio"> -->
        <%#= label :status, 'Activ' %>
        <%#= form.radio_button :status, "active", :checked => true %>
        <%#= label :status, 'Obsolete' %>
        <%#= form.radio_button :status, "obsolete", :checked => true %>
      <!-- </div> -->
    <!-- </div> -->
    <br><br>


    <div class="actions">
      <%= form.submit "Save", class: "btn btn-success btn-shadow" %>
    </div>
  <% end %>
</div>

app/views/products/_use_part_fields.html.erb
<%= form_with model: @use_part do |form| %>
  <!-- <%# if @use_part.errors.any? %>
    <div id="error_explanation">
      <h2><%#= pluralize(use_part.errors.count, "error") %> prohibited this use_part from being saved:</h2>

      <ul>
        <%#use_part.errors.each do |error| %>
          <li><%#= error.full_message %></li>
        <%# end %>
      </ul>
    </div>
  <%# end %> -->

  <div class="field">
    <%#= form.label :Product_id %><br>
    <%#= form.text_field :product_id %><br>
    <%= form.label :use_quantity %><br>
    <%= form.text_field :qty %>
    <br><br>
  </div>
  <div class="actions">
    <%= form.submit "Use" %>
   
  </div>
<% end %>
<br><br>

app/views/products/add.html.erb
<div class="min-height">
  <div class="card card-body bg-light">
    <h4 class="max_qty">
      Inventory: <%= @product.qty %>
    </h4>
    <br><br>

    <%= form_with(url: add_product_product_path(@product),local: true) do |form| %>
      <% if @product.errors.any? %>
        <div id="error_explanation">
          <h2>Error:</h2>

          <ul>
            <% @product.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="field">
        <%= form.label :qty_add %>
        <%= form.number_field :qty_add, value: params[:qty_add], min: '0', step: '1'  %>
      </div>
    <br><br>
      <div class="actions">
        <%# if @product.qty >= params[:qty].to_i  %>
          <%= form.submit "Add", class: "btn btn-primary " %>
        <%# end %>
      </div>
    <% end %>
  </div>
  <div class="back-buttons">
    <%= link_to '<< Back', products_path %>
  </div>
</div>

app/views/products/edit.html.erb
<div class="min-height">
	<h1 class="top-mobile-screen">Editing Product</h1>

	<%= render 'form', product: @product %>
	<br><br>
	<%= link_to 'Show', @product %> |
	<%= link_to 'Back', products_path %> |
	<%= link_to 'Products', products_path %>
</div>

app/views/products/index.html.erb
<div class="min-height">
  <h1 class="top-mobile-screen">Parts</h1>
  
  <span>
    <%= form_tag products_path, :method => 'get' do %>
      <%= hidden_field_tag :direction, params[:direction] %>
      <%= hidden_field_tag :sort, params[:sort] %>
      <div class="row">
        <div class="col-sm-12 col-xs-12 col-md-4 col-lg-2">
          <%= text_field_tag :search, params[:search], id: 'search' %>
        </div>
        <div class="col-sm-12 col-xs-12 col-md-6 col-lg-4">  
          <div class="row">
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-3">
              <%= submit_tag "Search", :name => nil, class: "btn btn-primary btn-custom-class btn-shadow" %>
            </div>
            
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-3">
              <%= button_tag 'CLEAR', id: 'clear_form_button', class: "btn btn-warning btn-custom-class btn-shadow" %>
            </div>
          </div> 
        </div>
      </div>
    <% end %>
    <%= javascript_pack_tag 'clear' %>
  </span>


  <% if current_user.try(:type) == 'AdminUser' %>
    <span class="new_product">
      <%= link_to 'New Product', new_product_path %>
    </span>
  <% end %>
  <br>
  <table class='table table-striped table-responsive-md btn-table'>
    <%= form_with url: print_labels_products_url, local: true, method: :post do |form| %>
    <thead>
      <tr class="sort-table">
        <th class="hide-content hide-medium">ID</th>
        <% if current_user.try(:type) == 'AdminUser' || current_user.try(:type) == 'SuperUser' %>
          <th class="hide-content hide-medium">
            <input type="checkbox" id="selectAll" value="selectAll">
            <%= form.submit "Labels", data: { disable_with: false } %>
          </th>
        <% end %>
        <th><%= sortable "item_no", "Item #" %></th>
        <th><%= sortable "description" %></th>
        <th class="hide-content"><%= sortable "supplier_number", "Supplier #" %></th>
        <th><%= sortable "qty" %></th>
        <th class="hide-content"><%= sortable "location" %></th>
        <th class="hide-content hide-medium"><%= sortable "supplier_name" %></th>
        <th class="hide-content hide-medium"><%= sortable "manufacturer_name", "Man. name" %></th>
        <th class="hide-content hide-medium"><%= sortable "manufacturer_no", "Man. #" %></th>
        <th><%= sortable "status" %></th>
        <!-- <th>QR-Code</th> -->
        <% if current_user.try(:type) == 'AdminUser' || current_user.try(:type) == 'SuperUser' %>
          <th class="hide-content" colspan="2"></th>
        <% end %>  
      </tr>
    </thead>
  <!---------------- check all checkboxes --------------->
    <script type='text/javascript'>
      // $('#selectAll').click(function() {
      //    if (this.checked) {
      //        $(':checkbox').each(function() {
      //            this.checked = true;                        
      //        });
      //    } else {
      //       $(':checkbox').each(function() {
      //            this.checked = false;                        
      //        });
      //    } 
      // });

      $('#selectAll').click(function (event) {
        if (this.checked) {
          $(':checkbox').each(function () {
            this.checked = true;
          });
        } else {
          $(':checkbox').each(function () {
            this.checked = false;
          });
        }
      });
    </script>
  <!---------------- check all checkboxes --------------->

    <tbody>
      <% @products.each_with_index do |product, index| %>
        <%# if product.status == "active" %>
        <% if product.status != "active" %>
          <tr class="obsolete" >
        <% elsif !product.featured_image.attached? %>
          <tr class="no_image_table_color">
        <% else %>
          <tr>
        <% end %>
            <td class="hide-content hide-medium"><%= product.id %></td>
            <!-- <td class="hide-content hide-medium"><%#= "#{index + 1}" %></td> -->
            <% if current_user.try(:type) == 'AdminUser' || current_user.try(:type) == 'SuperUser' %>
              <td class="hide-content hide-medium">
                <% if product.status == "active" %>
                  <%= form.check_box :products_ids, {multiple: true}, product.id %>
                <% end %>    
              </td>
            <% end %>
            <td><%=  link_to truncate(product.item_no.upcase.truncate(12)).html_safe, product %></td>
            <td><%= link_to truncate(product.description.truncate(32)).capitalize.html_safe, product if product.description %></td>
            <td class="hide-content"><%= product.supplier_number.upcase.truncate(16) if product.supplier_number %></td>
            <td><%= product.qty %></td>
            <td class="hide-content"><%= product.location.upcase.truncate(8) if product.location %></td>
            <td class="hide-content hide-medium"><%= product.supplier_name.truncate(16) if product.supplier_name %></td>
            <td class="hide-content hide-medium"><%= product.manufacturer_name.truncate(16) if product.manufacturer_name %></td>
            <td class="hide-content hide-medium"><%= product.manufacturer_no.truncate(16) if product.manufacturer_no %></td>
            <!-- <td><%#= QrCode.call(product_url(product))%></td> -->
            <% if current_user.try(:type) != 'AdminUser' && current_user.try(:type) != 'SuperUser' %>
              <td><%= link_to 'Use', use_product_path(product), class: "btn btn-primary" %></td>
            <% end %>
            <!-- <td>
              <%#= link_to 'Show', product %>
            </td> -->
            <% if current_user.try(:type) == 'AdminUser' || current_user.try(:type) == 'SuperUser' %>

              <td class="hide-content">
                <%= link_to edit_product_path(product) do%>
                  <i class="fa fa-edit" width="50px" height="50px"></i>  
                <% end %>
              </td>
              <td>
                <%= link_to "Delete", product, method: :delete, data: { confirm: 'Are you sure you want to delete record?' }, class: "btn btn-danger btn-sm"%>
              </td>
            <% end %>
          </tr>
        <% end %>

      <% end %>
    </tbody>
  </table>
  <div class="paginate">
    <%= will_paginate @products, renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer, previous_label: "<<", next_label: ">>", inner_window: 1, outer_window: 1 %>
    
      <h6 class="go-to-page"> Go To Page:</h6> 
      <span class="select-page">
        <%= will_paginate(@products, pagination_options) %>
      </span> 
      <script type='text/javascript'>
        // jQuery(document).ready(function($) {
          // trigger pagination
          $(".pagination form select").change(function(e) {
            $(this).parent("form").submit();
          });
        // });


        
      </script> 
  </div>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<div class="back-buttons">
	<%= link_to '<< Back', products_path %>
</div>

app/views/products/show.html.erb
<div class="min-height">
  <h3 class="top-mobile-screen">
    <strong>Name:</strong>
    <u>
      <%= @product.description.capitalize %>
    </u>
  </h3>
  <h4 class="inventory">
    Inventory: 
    <%= @product.qty %>
  </h4>

<% if @product.status == "active" %>
  <div class="card card-body bg-light">
<% else %>
  <div class="card card-body " style="background-color: #ffa791;">
<% end %>

    <div class="row">
      <div class="col-12 col-md-8 col-lg-6">
        <div class="row">
          <div class="col-sm-12 col-xs-12 col-lg-9">
            <div class="card card-body bg-light ">
              <h6 class="prod-details">Item #:
                <span>
                  <% if @product.item_no? %>
                    <%= @product.item_no.capitalize %>
                  <% else %>
                    <h6>N/A</h6>
                  <% end %>
                </span>
              </h6>
            </div>
            <div class="card card-body bg-light prod-details ">
              <h6 class="prod-details">Supplier #:
                <span>
                  <% if @product.supplier_number? %>
                    <%= @product.supplier_number.capitalize %>
                  <% else %>
                    <h6>N/A</h6>
                  <% end %>
                </span>
              </h6>
            </div>
            <div class="card card-body bg-light prod-details">
              <h6 class="prod-details">Supplier Name:
                <span>
                  <% if @product.supplier_name? %>
                    <%= @product.supplier_name.capitalize %>
                  <% else %>
                    <h6>N/A</h6>
                  <% end %> 
                </span>
              </h6>
            </div>
            <div class="card card-body bg-light prod-details">
              <h6 class="prod-details">Location:
                <span>
                  <% if @product.location? %>
                    <%= @product.location.capitalize %>
                  <% else %>
                    <h6>N/A</h6>
                  <% end %>
                </span>
              </h6>
            </div>
            <div class="card card-body bg-light prod-details">
              <h6 class="prod-details">Manufacturer Name:
                <span>
                  <% if @product.manufacturer_name? %>
                    <%= @product.manufacturer_name.capitalize %>
                  <% else %>
                    <h6>N/A</h6>
                  <% end %>
                </span>
              </h6>
            </div>
            <div class="card card-body bg-light prod-details">
              <h6 class="prod-details">Manufacturer #:
                <span>
                  <% if @product.manufacturer_no? %>
                    <%= @product.manufacturer_no.capitalize %>
                  <% else %>
                    <h6>N/A</h6>
                  <% end %>
                </span>
              </h6>
            </div>
            
          </div>
          <div class="col-sm-12 col-xs-12 col-lg-3">
            <%= QrCode.call(product_url(@product))%>
          </div>
        </div>
        
      </div>
      
      <div class="col-12 col-md-4 col-sm-12 col-lg-6">
        <div class="product-image">
          <% if @product.featured_image.attached? %>
            <%= image_tag @product.featured_image, style: "width: 350px; display: block;", class: "img-responsive" %>
          <% else %>
            <div class="no-image">No image available...</div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

    <div class="row show-buttons">
      <div class="col-md-3">
        <%= link_to 'Use', use_product_path(@product), class: "btn btn-danger btn-block btn-shadow" %>
      </div>
      <div class="col-md-6">
      </div>
      <div class="col-md-3">
        <% if current_user.try(:type) == 'AdminUser' || current_user.try(:type) == 'SuperUser' %>
          <%= link_to 'Add', add_product_path(@product), class: "btn btn-primary btn-block btn-shadow" %>
        <% end %>
      </div>
    </div>

  <div class="back-buttons">
    <% if current_user.try(:type) == 'AdminUser' %>
      <%= link_to 'Edit', edit_product_path(@product) %>  | 
    <% end %>
    <%= link_to 'Back', :back %> |
    <%= link_to 'Products', products_path %>
  </div>

</div>

app/views/products/use.html.erb
<div class="min-height">
  <div class="card card-body bg-light">
    <h4 class="max_qty">
      Inventory: <%= @product.qty %>
    </h4>
    <br><br>

    <%= form_with(url: do_use_product_path(@product),local: true) do |form| %>
      <% if @product.errors.any? %>
        <div id="error_explanation">
          <h2>Error:</h2>

          <ul>
            <% @product.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="field">
        <%= form.label :qty %>
        <%= form.number_field :qty, value: params[:qty], min: '0', step: '1'  %>
      </div>
    <br><br>
      <div class="actions">
        <%# if @product.qty >= params[:qty].to_i  %>
          <%= form.submit "Use", class: "btn btn-primary " %>
        <%# end %>
      </div>
    <% end %>
  </div>

  <div class="back-buttons">
    <%= link_to '<< Back', products_path %>
  </div>
</div>